// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wangkai/Downloads/dumi-dumy/packages/ui/node_modules/dumi/theme-default/slots/PreviewerActionsExtra/index.js';
