// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from '/Users/wangkai/Downloads/dumi-dumy/node_modules/.pnpm/@umijs+renderer-react@4.0.55_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context: {} }, container);
}
